depot/depot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from depotapp.views import login_view,logout_view
urlpatterns = [
    # Examples:
    # url(r'^$', 'depot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^depot/', include('depotapp.urls',namespace="depotapp")),
    url(r'^accounts/login/$', login_view),
    url(r'^accounts/logout/$', logout_view),
    url(r'^search/', include('haystack.urls')),
]

depot/depotapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [url(r'^$',views.index,name='index'),
				url(r'^shouye/$',views.shouye,name='shouye'),
				url(r'^regist/$',views.register,name='regist'),
				url(r'^product/(?P<product_id>[0-9]+)/$',views.product_detail,name='product_detail'),
				url(r'^seller/$',views.seller_list,name='seller_list'),
				url(r'^seller/(?P<user_id>[0-9]+)/seller_store/$',views.seller_store,name='seller_store'),
				url(r'^store/(?P<store_id>[0-9]+)/edit/$',views.store_detail_edit,name='store_detail_edit'),
				url(r'^seller/(?P<user_id>[0-9]+)/add_store/$',views.add_store,name='add_store'),
				url(r'^store/(?P<store_id>[0-9]+)/add_product/$',views.add_product,name='add_product'),
				url(r'^store/(?P<store_id>[0-9]+)/detail/$',views.store_detail,name='store_detail'),
				url(r'^buyer/(?P<user_id>[0-9]+)/shopping_cart/(?P<cart_id>[0-9]+)/$',views.shopping_cart,name='shopping_cart'),
				url(r'^buyer/(?P<user_id>[0-9]+)/add_to_shopping_cart/(?P<product_id>[0-9]+)/$',views.add_to_shopping_cart,name='add_to_shopping_cart'),
				url(r'^buyer/(?P<user_id>[0-9]+)/cart/(?P<cart_id>[0-9]+)/payment/$',views.payment,name='payment'),
				url(r'^buyer/(?P<user_id>[0-9]+)/clear/(?P<cart_id>[0-9]+)/$',views.clear_cart,name='clear_cart'),
				url(r'^buyer/(?P<user_id>[0-9]+)/recharge/$',views.recharge,name='recharge'),
				url(r'^buyer/(?P<user_id>[0-9]+)/pay_single/product/(?P<product_id>[0-9]+)/$',views.pay_single,name='pay_single'),
				url(r'^buyer/(?P<user_id>[0-9]+)/order_page/$',views.order_page,name='order_page'),
				url(r'^buyer/(?P<user_id>[0-9]+)/confirm_receipt/(?P<order_id>[0-9]+)/$',views.confirm_receipt,name='confirm_receipt'),
				url(r'^seller/(?P<user_id>[0-9]+)/confirm_deliver/(?P<order_id>[0-9]+)/$',views.confirm_deliver,name='confirm_deliver'),
				url(r'^buyer/delete/(?P<order_id>[0-9]+)/$',views.delete_order,name='delete_order'),
				url(r'^buyer/delete_all_order/$',views.delete_all_order,name='delete_all_order'),
				url(r'^seller/(?P<user_id>[0-9]+)/order_unsolve/$',views.order_unsolve,name='order_unsolve'),
				url(r'^seller/(?P<user_id>[0-9]+)/order_solved/$',views.order_solved,name='order_solved'),
				url(r'^search_product/$',views.search_product,name='search_product'),
				url(r'^store_product/(?P<store_id>[0-9]+)/$',views.store_product,name='store_product'),
				url(r'^unknown/$',views.unknown,name='unknown'),
]

depot/depotapp/models.py
#--coding=utf-8
from django.db import models
#from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
# Create your models here.
class User(AbstractUser,models.Model):
	#user_name = models.CharField(max_length=100,unique=True)
	#password = models.SlugField(max_length=6)
				#user=models.OneToOneField(User,unique=True,verbose_name=('用户'))
	user_register_time = models.DateTimeField('date to register',auto_now_add=True)
	is_buyer = models.NullBooleanField()
	Tel = models.CharField(max_length=20,blank=True)
	account = models.DecimalField(max_digits=24,decimal_places=2,default=0.00)
	def __unicode__(self):
		return self.username#返回unicode
class Store(models.Model):
	store_name = models.CharField(max_length=100,unique=True)
	store_type = models.CharField(max_length=100)
	store_addr = models.CharField(max_length=200)
	description=models.TextField()
	store_register_time = models.DateTimeField('date to register')
	store_product_num = models.PositiveIntegerField(default = 0)
	seller = models.ForeignKey(User)
	def __unicode__(self):
		return self.store_name#返回unicode
class Product(models.Model):
	title = models.CharField(max_length=100)
	description=models.TextField()
	image_url = models.CharField(max_length=200)
	price = models.DecimalField(max_digits=8,decimal_places=2)
	time_to_market =models.DateTimeField('date to market')
	store = models.ForeignKey(Store)
	def img(self):
		return self.image_url.encode('utf-8')
	def __unicode__(self):
		return self.title#返回unicode
class Cart(models.Model):
	total_price = models.DecimalField(max_digits=24,decimal_places=2)
	user = models.ForeignKey(User)
class Lineitem(models.Model):
	cart_name = models.ManyToManyField(Cart)
	quantity = models.IntegerField(default = 1)
	unit_price = models.DecimalField(max_digits=8,decimal_places=2)
	time_to_cart =models.DateTimeField('date to cart')
	item_price = models.DecimalField(max_digits=24,decimal_places=2)
	pro_item = models.ForeignKey(Product)
class Myorder(models.Model):
	order_time =models.DateTimeField('date to order')
	deliver_time =models.DateTimeField('date to deliver',null=True)
	received_time =models.DateTimeField('date to receive',null=True)
	buyer_del = models.BooleanField(default=False)
	seller_del = models.BooleanField(default=False)
	is_receiver = models.BooleanField(default=False)
	is_deliver =models.BooleanField(default=False)
	buyer = models.CharField(max_length=100)
	seller= models.CharField(max_length=100)
	product =models.ForeignKey(Product)
	quantity = models.IntegerField(default = 1)
	order_price = models.DecimalField(max_digits=24,decimal_places=2,default=0.00)
	user = models.ManyToManyField(User)

depot/depotapp/forms.py
#--coding=utf-8
from django import forms
class LoginForm(forms.Form):
	username = forms.CharField(label='用户名',max_length=50)
	password = forms.CharField(label='密码',widget=forms.PasswordInput())
	#email = forms.EmailField(label='邮箱')
	#Tel = forms.CharField(label='电话',max_length=20)
class RegisterForm(forms.Form):
	username = forms.CharField(label='用户名',max_length=50)
	password = forms.CharField(label='密码',widget=forms.PasswordInput())
	email = forms.EmailField(label='邮箱')
	Tel = forms.CharField(label='电话',max_length=20)
	Choices = (('level1',True),('level2',False))
	Is_buyer = forms.ChoiceField(choices=Choices,label='选择用户类型')
class Store_detail_EditForm(forms.Form):
	store_name = forms.CharField(label='店铺名',max_length=50)
	store_type = forms.CharField(label='店铺类型',max_length=50)
	store_addr = forms.CharField(label='店铺地址',max_length=100)
	description = forms.CharField(label='店铺简介',max_length=100,required=False,widget=forms.Textarea(attrs={'cols':'80','rows':'5'}) )
class Add_product_Form(forms.Form):
	product_name = forms.CharField(label='商品名',max_length=50)
	description = forms.CharField(label='商品简介', max_length=100, required=False,
								  widget=forms.Textarea(attrs={'cols': '80', 'rows': '5'}))
	price = forms.DecimalField(decimal_places=2)
class Recharge_Form(forms.Form):
	amount = forms.DecimalField(decimal_places=2)
class SearchForm(forms.Form):
	search = forms.CharField(label='搜索',max_length=100)

depot/depotapp/views.py
#--coding=utf-8
from django.shortcuts import render,get_object_or_404,render_to_response,redirect
from .models import Store,Product,User,Cart,Lineitem,Myorder
#from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
#from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate,login,logout
from .forms import LoginForm,RegisterForm,Store_detail_EditForm,Add_product_Form,Recharge_Form,SearchForm
import datetime
from django.utils import timezone
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.template import loader, RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from PIL import Image
# Create your views here.

#数据操作的user.id都没做判断
@csrf_exempt
def login_view(request):
	#网上为username=request.POST['username'],不可用
	#user = authenticate(username=request.POST.get('username'),password=request.POST.get('password'))
	#if user is not None:
	#	login (request,user)
	#	print request.user
	#	return index(request)
	#else:
	if request.method == 'POST':
		loginform = LoginForm(request.POST)
		if loginform.is_valid():
			username =loginform.cleaned_data['username']
			password =loginform.cleaned_data['password']
			#user = User.objects.filter(username__exact=username,password__exact=password)
			user = authenticate(username=username,password=password
			)
			print user
			if user:
				login(request,user)
				if user.is_buyer:
					return redirect(reverse('depotapp:shouye'))
				else:
					print request.user
					print request.user.id
					return redirect(reverse('depotapp:seller_store',args=(user.id,)))
			return render_to_response('login.html',{'loginform':loginform})
	else:
		loginform = LoginForm()
		return render_to_response('login.html',{'loginform':loginform})
def logout_view(request):
	logout(request)
	return redirect(reverse('depotapp:index'))
@csrf_exempt
def register(request):
	if request.method == 'POST':
		registerform = RegisterForm(request.POST)
		if registerform.is_valid():
			username = registerform.cleaned_data['username']
			password = registerform.cleaned_data['password']
			email  =registerform.cleaned_data['email']
			Tel =registerform.cleaned_data['Tel']
			choice = registerform.cleaned_data['Is_buyer']
			if choice == 'level1':
				is_buyer=True
			else:
				is_buyer=False
			user_register_time = timezone.now()
			user=User.objects.create_user(username=username,password=password,email=email,Tel =Tel,is_buyer=is_buyer,user_register_time=user_register_time)
			print user.is_buyer
			if user.is_buyer==True:
				return HttpResponse('注册成功')
			else:
				return redirect(reverse('depotapp:seller_store',args=(user.id,)))

			#profile=UserProfile(user_id=user.id,Tel =Tel,is_buyer=is_buyer,user_register_time=user_register_time)
			#profile.save()

	else:
		registerform =RegisterForm()
	return render_to_response('regist.html',{'registerform':registerform,'title':'注册啦啦啦'})

def index(request):
	product_list = Product.objects.order_by('-time_to_market')[:20]
	return render(request,'depotapp/index.html',{'product_list':product_list})

def search_product(request):
	q = request.GET.get('q')
	if not q:
		error_msg = '请输入要搜索的商品'
		return render(request, 'depotapp/search_product_result.html', {'error_msg': error_msg})
	result_list = Product.objects.filter(title__icontains=q)
	return render(request, 'depotapp/search_product_result.html', {'result_list': result_list})
def product_detail(request,product_id):
	product = get_object_or_404(Product,pk= product_id)
	if request.user.cart_set.all():
		cart = request.user.cart_set.all()[0]
	else:
		cart = Cart(total_price=0, user=request.user)
		cart.save()
	return render(request,'depotapp/product_detail.html',{'cart':cart,'product':product,'user':request.user})

def store_product(request,store_id):
	store = get_object_or_404(Store, pk=store_id)
	product_list = Product.objects.filter(store=store)
	return  render(request,'depotapp/store_product.html',{'product_list':product_list})
@login_required
def seller_list(request):
	print request.user,'aaa'
	if not request.user.is_buyer:
		list = Product.objects.order_by('-time_to_market')
		product_list =[]
		for product in list:
			if product.store.seller.id == request.user.id:
				product_list.append(product)
		return render(request,'depotapp/seller_list.html',{'product_list':product_list})
	else:
		return HttpResponse('禁止访问')

@login_required
def seller_store(request,user_id):
	print user_id
	user = get_object_or_404(User,pk=user_id)
	store_list = user.store_set.all()
	return render_to_response('depotapp/store_list.html',{'store_list':store_list,'user':user})
@login_required
@csrf_exempt
def store_detail_edit(request,store_id):
	print '======================'
	store = get_object_or_404(Store,pk= store_id)
	data = {'store_name':store.store_name,'store_type':store.store_type,'store_addr':store.store_addr,'description':store.description}
	if request.method == 'POST':
		store_form =Store_detail_EditForm(request.POST)
		print store_form.errors,'gagadhah'
		if store_form.is_valid():
			store.store_name = store_form.cleaned_data['store_name']
			store.store_addr = store_form.cleaned_data['store_addr']
			store.description = store_form.cleaned_data['description']
			store.store_type = store_form.cleaned_data['store_type']
			store.save()
			print u'保存成功'
			return redirect(reverse('depotapp:seller_store',args=(store.seller.id,)))
		else:
			print 'wuxiao'
			return render(request,'store_detail_edit.html',{'store':store,'store_form':store_form})
	else:
		store_form = Store_detail_EditForm(initial=data)
		return render(request,'store_detail_edit.html',{'store':store,'store_form':store_form})
@csrf_exempt
@login_required
def add_store(request,user_id):
	store = Store()
	if request.method=='POST':
		store_form =Store_detail_EditForm(request.POST)
		if store_form.is_valid():
			store.store_name = store_form.cleaned_data['store_name']
			store.store_addr = store_form.cleaned_data['store_addr']
			store.description = store_form.cleaned_data['description']
			store.store_type = store_form.cleaned_data['store_type']
			store.store_register_time = timezone.now()
			store.seller = request.user
			store.save()
			print u'添加成功'
			return redirect(reverse('depotapp:seller_store',args=(store.seller.id,)))
		else:
			print 'wuxiao'
			return render(request,'add_store.html',{'store':store,'store_form':store_form})
	else:
		store_form = Store_detail_EditForm()
		return render(request,'add_store.html',{'user':request.user,'store_form':store_form})
@csrf_exempt
@login_required
def add_product(request,store_id):
	store = get_object_or_404(Store, pk=store_id)
	product = Product()
	if request.method=='POST':
		product_form =Add_product_Form(request.POST)
		if product_form.is_valid():
			product.title = product_form.cleaned_data['product_name']
			product.description = product_form.cleaned_data['description']
			product.price = product_form.cleaned_data['price']
			product.time_to_market = timezone.now()
			product.store = store
			try:
				reqfile = request.FILES['picfile']
				img = Image.open(reqfile)
				img.thumbnail((500,500),Image.ANTIALIAS)
				name = product.title
				img.save("E:\\gitprojects\\django1\\depot\\depotapp\\templates\\static\\images\\%s.gif"%name,"gif")
				product.image_url = name+'.gif'
			except Exception,e:
				return HttpResponse("Error %s"%e)#异常，查看报错信息
			product.save()
			print u'添加商品成功'
			return redirect(reverse('depotapp:store_detail',args=(store.id,)))
		else:
			print 'wuxiao'
			return render(request,'add_product.html',{'store':store,'product_form':product_form})
	else:
		product_form = Add_product_Form()
		return render(request,'add_product.html',{'store':store,'product_form':product_form})
@login_required
def store_detail(request,store_id):
	if not request.user.is_buyer:
		store = get_object_or_404(Store, pk=store_id)
		product_list = store.product_set.all().order_by('-time_to_market')
		return render(request,'depotapp/store_detail.html',{'product_list':product_list,'store':store})
	else:
		return HttpResponse('禁止访问')

@login_required
def shouye(request):
	print request.user
	products_list = Product.objects.order_by('-time_to_market')
	p = Paginator(products_list, 3)
	page = request.GET.get('page')
	try:
		product_list = p.page(page)
	except PageNotAnInteger:
		product_list = p.page(1)
	except EmptyPage:
		product_list = p.page(p.num_pages)
	if request.user.cart_set.all():
		cart=request.user.cart_set.all()[0]
	else:
		cart =Cart(total_price=0,user=request.user)
		cart.save()
	return render(request,'depotapp/shouye.html',{'cart':cart,'product_list':product_list,'title':'首页'})
@login_required
def add_to_shopping_cart(request,user_id,product_id):
	user = get_object_or_404(User, pk=user_id)
	if product_id == '0':

		print cart
		return HttpResponse('无效商品')
	product = get_object_or_404(Product, pk=product_id)
	if not user.cart_set.all():
		cart =Cart(total_price=0,user=user)
		cart.save()
		lineitem=Lineitem(unit_price=product.price,time_to_cart=timezone.now(),item_price=product.price,pro_item=product)
		lineitem.save()
		lineitem.cart_name.add(cart)
		lineitem.save()
		cart.total_price +=lineitem.item_price
	else:
		cart=user.cart_set.all()[0]
		item=cart.lineitem_set.filter(pro_item=product)
		if item:
			item[0].quantity +=1
			item[0].item_price +=item[0].unit_price
			item[0].save()
			cart.total_price += item[0].unit_price
		else:
			lineitem=Lineitem(unit_price=product.price,time_to_cart=timezone.now(),item_price=product.price,pro_item=product)
			lineitem.save()
			lineitem.cart_name.add(cart)
			lineitem.save()
			cart.total_price +=lineitem.item_price
	cart.save()
	return redirect(reverse('depotapp:shopping_cart',args=(user.id,cart.id)))

@login_required
def clear_cart(request,user_id,cart_id):
	user = get_object_or_404(User, pk=user_id)
	cart = get_object_or_404(Cart, pk=cart_id)
	items = cart.lineitem_set.all()

depot/depotapp/templates/depotapp/base1.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
<head>
  <meta charset="UTF-8">
  {%if title%}
  <title>{{title}}</title>
  {%else%}
  <title>啦啦啦网</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
  <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{%static 'js/moment.min.js' %}"></script>
  {%endif%}
	<style type="text/css">
	ul#nav{ width:100%; height:60px; background:#C8C8C8;margin:0 auto} 
	ul#nav li{display:inline; height:60px} 
	ul#nav li a{display:inline-block; padding:0 15px; height:60px; line-height:60px;
	color:#FFF; font-family:"\5FAE\8F6F\96C5\9ED1"; font-size:16px} 
	ul#nav li a:hover{background:#0095BB}/*设置鼠标滑过或悬停时变化的背景颜色*/ 
	a:link {text-decoration: none;color:red;}
	a:visited {color:green；text-decoration:none;}
	a:hover  {color:blue;text-decoration:underline;}
	a:active {color:orange;text-decoration:blink;}
	body {  
    background:#3d71b8 url({%static 'images/120.jpg'%});  
    background-size: cover;
	background-attachment: fixed; 
    background-position:center;
	background-repeat:no-repeat;
	-webkit-background-size: cover;
    -o-background-size: cover;
}  
	</style>
</head>
<body>
    <div class="container">
      <div class="navbar">
        <div class="navbar-inner">
			<ul id="nav"> 
			<span>
			  <li><a href={%url 'depotapp:shouye'%}>首页</a></li> 
			  <li><a href={%url 'depotapp:recharge' user.id%}>我的账户</a></li> 
			  <li><a href={%url 'depotapp:order_page' user.id%}>我的订单</a></li> 
			  <li><a href={%url 'depotapp:shopping_cart' user.id cart.id%}>我的购物车</a></li> 
			  <li><a href={%url 'depotapp:unknown'%}>收藏店铺</a></li> 
			  <li><a href={%url 'depotapp:unknown'%}>关注卖家</a></li>
			  <li><a href='/accounts/logout/'>退出登录</a></li>
			</span>
			</ul> 
		</div>
	  </div>
	</div>
	<div>
		<form action="{%url 'depotapp:search_product'%}" method="get" name="search">
			{%csrf_token%}
			<input type="search" name="q" placeholder="搜索商品" required>
		</form>
	</div>
	<div>
		<form action="/search/" method="get" name="search">
			{%csrf_token%}
			<input type="search" name="q" placeholder="搜索店铺" required>
		</form>
	</div>
  {%block content%}{%endblock%}
</body>
</html>

depot/depotapp/templates/depotapp/base2.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="UTF-8">
  {%if title%}
  <title>{{title}}</title>
  {%else%}
  <title>啦啦啦网</title>
  {%endif%}
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
  <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{%static 'js/moment.min.js' %}"></script>
	<style type="text/css">
	ul#nav{ width:100%; height:60px; background:#00A2CA;margin:0 auto}
	ul#nav li{display:inline; height:60px}
	ul#nav li a{display:inline-block; padding:0 20px; height:60px; line-height:60px;
	color:#FFF; font-family:"\5FAE\8F6F\96C5\9ED1"; font-size:16px}
	ul#nav li a:hover{background:#0095BB}/*设置鼠标滑过或悬停时变化的背景颜色*/
	a:link {text-decoration: none;color:red;}
	a:visited {color:green；text-decoration:none;}
	a:hover  {color:blue;text-decoration:underline;}
	a:active {color:orange;text-decoration:blink;}
	body {  
    background:#3d71b8 url({%static 'images/120.jpg'%});  
    background-size: cover;
	background-attachment: fixed; 
    background-position:center;
	background-repeat:no-repeat;
	-webkit-background-size: cover;
    -o-background-size: cover;
	</style>
</head>
<body>
<ul id="nav">
    <li><a href={%url 'depotapp:seller_store' user.id%}>店铺列表</a></li>
    <li><a href={%url 'depotapp:seller_list'%}>商品列表</a></li>
    <li><a href={%url 'depotapp:order_solved' user.id%}>已处理订单</a></li>
    <li><a href={%url 'depotapp:order_unsolve' user.id%}>待处理订单</a></li>
    <li><a href={%url 'depotapp:recharge' user.id%}>我的账户</a></li>
    <li><a href='/accounts/logout/'>退出登录</a></li>
</ul>
  {%block content%}{%endblock%}
</body>
</html>

depot/depotapp/templates/depotapp/myorder.html
{%extends "base1.html"%}
{%block content%}
<h1>我的订单</h1>
<p><span><a href={%url 'depotapp:delete_all_order' %}>删除所有订单</a></span>&nbsp;&nbsp;<span>慎点！</span></p>
{%for order in order_list%}
{%if not order.buyer_del%}
<p>
	<div><span>订单号：{{order.id}}</span>&nbsp;&nbsp;&nbsp;
		{%if order.is_receiver%}
		<span><a href={%url 'depotapp:delete_order' order.id%}>删除订单</span></div>
		{%endif%}
	<div><i><img src='/static/images/{{order.product.img}}' alt="Hi!" /></i></div>
	<div><a href={%url 'depotapp:product_detail' order.product.id%}><strong>商品：{{order.product.title}}</strong></a></div>
	<div><i>单价：{{order.product.price}}</i></div>
	<div><i>数量：{{order.quantity}}</i></div>
	<div><i>总计：{{order.order_price}}</i></div>
	<div><span><i>店铺：{{order.product.store.store_name}}</i></span>&nbsp;&nbsp;&nbsp;<span><i>店长：{{order.seller}}</i></span></div>
	<div><i>下单时间：{{order.order_time}}</i></div>
	{%if order.is_deliver%}
	<div><i>发货时间：{{order.deliver_time}}</i></div>
	{%endif%}
	{%if order.is_receiver%}
	<div><i>收货时间：{{order.received_time}}</i></div>
	{%endif%}
	{%if not order.is_deliver%}
	<div><b>待发货</b></div>
	{%else%}
	{%if not order.is_receiver%}
	<div><b>已发货，正在配送中...</b></div>
	<div><a href={%url 'depotapp:confirm_receipt' user.id order.id%}><b>确认收货</b></a></div>
	{%else%}
	<div><b>已确认收货</b></div>
	{%endif%}
	{%endif%}
	<div></div>
	<hr>
</p>
{%endif%}
{%endfor%}

<div class="pagination">
    <span class="step-links">
        {% if order_list.has_previous %}
            <a href="?page={{ order_list.previous_page_number }}">上一页</a>
        {% endif %}
 
        <span class="current">
            第 {{ order_list.number }} 页/共 {{ order_list.paginator.num_pages }} 页
        </span>
 
        {% if order_list.has_next %}
            <a href="?page={{ order_list.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>
{%endblock%}

depot/depotapp/templates/depotapp/shopping_cart.html
{%extends "base1.html"%}
{%block content%}
<h1>我的购物车</h1>
<p><a href='/accounts/logout/'>logout</a></p>
<p><a href={%url 'depotapp:clear_cart' user.id cart.id%}>清空购物车</a></p>
{%if productitem_list%}
{%for item in productitem_list%}
<p>
	<div><i><img src='/static/images/{{item.pro_item.img}}' alt="Hi!" /></i></div>
	<div><a href={%url 'depotapp:product_detail' item.pro_item.id%}><strong>{{item.pro_item.title}}</strong></a></div>
	<div><i>{{item.unit_price}}</i></div>
	<div><i>{{item.pro_item.store.store_name}}</i></div>
	<hr/>
</p>
<div><b>数量：{{item.quantity}}</b></div>
<div><b>价格：{{item.item_price}}</b></div>
<hr/>
{%endfor%}
{%endif%}
<div></div>
<hr/>
{%if cart.total_price%}
<div><b>待支付：￥{{cart.total_price}}</b></div>
<hr/>
<div><b><a href={%url 'depotapp:payment' user.id cart.id%}>立即支付</a></b></div>
{%endif%}
<div class="pagination">
    <span class="step-links">
        {% if productitem_list.has_previous %}
            <a href="?page={{ productitem_list.previous_page_number }}">上一页</a>
        {% endif %}
 
        <span class="current">
            第 {{ productitem_list.number }} 页/共 {{ productitem_list.paginator.num_pages }} 页
        </span>
 
        {% if productitem_list.has_next %}
            <a href="?page={{ productitem_list.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>
{%endblock%}